name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository_owner }}/blogfrontend
  BACKEND_IMAGE_NAME: ${{ github.repository_owner }}/blogbackend

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Application Version
      id: sem-version
      uses: paulhatch/semantic-version@v4.0.2

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
        tags: ${{ steps.sem-version.outputs.version }}

    - name: Build and Test
      uses: docker/build-push-action@v3
      with:
        context: ./src/Backend
        file: ./src/Backend/BlogBackend/Dockerfile
        target: test

    - name: Publish and Push
      uses: docker/build-push-action@v3
      with:
        context: ./src/Backend
        file: ./src/Backend/BlogBackend/Dockerfile
        build-args: |
          VERSION=${{ steps.sem-version.outputs.version }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GHCR
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
        tags: ${{ steps.sem-version.outputs.version }}

    - name: Build and Test
      uses: docker/build-push-action@v3
      with:
        context: ./src/Frontend/BlogFrontend
        file: ./src/Frontend/BlogFrontend/Dockerfile
        build-args: |
          VERSION=${{ steps.sem-version.outputs.version }}
        target: test

    - name: Publish and Push
      uses: docker/build-push-action@v3
      with:
        context: ./src/Frontend/BlogFrontend
        file: ./src/Frontend/BlogFrontend/Dockerfile
        build-args: |
          VERSION=${{ steps.sem-version.outputs.version }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
